name: erevho
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
    sdk: '>=2.17.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    # Data store.
    objectbox: ^2.1.0
    objectbox_flutter_libs: ^2.1.0
    # UUID generator.
    uuid: ^3.0.7
    # Entities helper package.
    freezed_annotation: ^2.2.0
    json_annotation: ^4.8.1
    # Icons packages.
    cupertino_icons: ^1.0.5
    # Dart code analyzer package. (Not the last version dues to Hive compatibility)
    analyzer: ^5.12.0
    # Routing package management.
    fluro: ^2.0.5
    # State management.
    flutter_riverpod: ^2.3.6
    # Translation provider.
    intl: ^0.18.0
    #
    path_provider: ^2.0.15
    path: ^1.8.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.2
    build_runner: ^2.4.6
    objectbox_generator: ^2.1.0
    freezed: ^2.3.5
    json_serializable: ^6.7.1

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/images/
