name: erevho
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.17.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    # Hive : NoSQL package.
    hive: ^2.2.2
    hive_flutter: ^1.1.0
    # UUID generator.
    uuid: ^3.0.6
    # DI package.
    injectable: ^1.5.3
    # DI package
    get_it: ^7.2.0
    # Entities helper package.
    freezed: ^2.0.3+1
    # Entities helper package.
    freezed_annotation: ^2.0.3
    # Entities parser package.
    json_annotation: ^4.5.0
    #Shared Preferences package.
    shared_preferences: ^2.0.15
    # Http request package.
    dio: ^4.0.6
    # http helper package.
    retrofit: ^3.0.1+1
    # Icons packages.
    cupertino_icons: ^1.0.2
    # Dart code analyzer package.
    analyzer: ^3.4.1
    # Routing package management.
    fluro: ^2.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0
    build_runner: ^2.1.11
    json_serializable: ^6.2.0

    # Generators packages.
    hive_generator: ^1.1.3
    retrofit_generator: ^4.0.1
    injectable_generator: ^1.5.3

flutter:
    uses-material-design: true
